### ISSUE TITLE
.NET Framework 4.6 runtime: SagaData with abstract base class

### ISSUE THREAD

**Issue by sveinfid** [Particular/NServiceBus.NHibernate#114]
After installing Visual Studio 2015, which includes the .NET Framework 4.6 runtime, I am receiving an error on startup when using SagaData with an abstract base class:

"NHibernate.MappingException: Could not compile the mapping document: mapping_by_code ---> NHibernate.MappingException: Cannot extend unmapped class"

Please have a look here for a minimal example:
https://github.com/sveinfid/NHibernateNETFramework46Bug

Note that the project is still targeting .NET 4.5.2. The project does not have to be upgraded to 4.6 for this to become an issue.

This may be related this issue which is about the ordering of the results returned by Assembly.GetTypes(), which has changed between .NET 4.5.2 and 4.6: http://stackoverflow.com/questions/31321275/nhibernate-mapping-by-code-in-net-4-6-throws-cannot-extend-unmapped-class#comment51373729_31321275

Full stack trace:
2015-07-31 11:36:12.566 ERROR NServiceBus.GenericHost Exception when starting en
dpoint.
NHibernate.MappingException: Could not compile the mapping document: mapping_by_
code ---> NHibernate.MappingException: Cannot extend unmapped class: NHibernateN
ETFramework46Bug.MySagaDataSuperClass, NHibernateNETFramework46Bug, Version=1.0.
0.0, Culture=neutral, PublicKeyToken=null
   at NHibernate.Cfg.XmlHbmBinding.ClassBinder.GetSuperclass(String extendsName)

   at NHibernate.Cfg.XmlHbmBinding.MappingRootBinder.AddEntitiesMappings(HbmMapp
ing mappingSchema, IDictionary`2 inheritedMetas)
   at NHibernate.Cfg.XmlHbmBinding.MappingRootBinder.Bind(HbmMapping mappingSche
ma)
   at NHibernate.Cfg.Configuration.AddDeserializedMapping(HbmMapping mappingDocu
ment, String documentFileName)
   --- End of inner exception stack trace ---
   at NHibernate.Cfg.Configuration.LogAndThrow(Exception exception)
   at NHibernate.Cfg.Configuration.AddDeserializedMapping(HbmMapping mappingDocu
ment, String documentFileName)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at NServiceBus.Features.NHibernateStorageSession.Setup(FeatureConfigurationCo
ntext context) in c:\BuildAgent\work\5135de308b2f3016\src\NServiceBus.NHibernate
\SharedSession\NHibernateStorageSession.cs:line 31
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureState feature
State, IEnumerable`1 featuresToActivate, FeatureConfigurationContext context) in
 c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActiva
tor.cs:line 240
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationCo
ntext context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Featu
res\FeatureActivator.cs:line 116
   at NServiceBus.Configure.Initialize() in c:\BuildAgent\work\3206e2123f54fce4\
src\NServiceBus.Core\Configure.cs:line 115
   at NServiceBus.Bus.Create(BusConfiguration configuration) in c:\BuildAgent\wo
rk\3206e2123f54fce4\src\NServiceBus.Core\Bus.cs:line 19
   at NServiceBus.GenericHost.PerformConfiguration(Action`1 moreConfiguration) i
n c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHos
t.cs:line 119
   at NServiceBus.GenericHost.Start() in c:\BuildAgent\work\a3de8759ee491634\src
\NServiceBus.Hosting.Windows\GenericHost.cs:line 58

**Comment by sveinfid** [comment]
Any progress on this issue?

I ended up rewriting to use an interface instead, but would be nice to be able to use an abstract base class too, as was possible pre-.NET Framework 4.6

**Comment by DavidBoike** [comment]
@Particular/nhibernate-persistence-maintainers I've verified this bug on Core 5.2.14, NSB.NH 6.2.7.

**Comment by SzymonPobiega** [comment]
Hi @sveinfid 

Thanks for the repro. I've tried it and it fails for me both for 4.5.2 and 4.6.0 frameworks consistently. I was able to reproduce it also in our unit tests. The problem seems to be `ContainSagaData`. When I changed your abstract class to implement `IContainSagaData` instead form inheriting from yet another abstract `ContainSagaData`, it worked. I am investigating further...

**Comment by SzymonPobiega** [comment]
Here's a potential fix: https://github.com/Particular/NServiceBus.NHibernate/pull/196 targeting the coming 7.0.0 release.
