### ISSUE TITLE
Using NServiceBus pre 5.2.8 with version 6.2.5 results in NullReferenceException

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.NHibernate#140]
Using NServiceBus version 5.2.4 with NServiceBus.NHibernate version 6.2.5 results in a NullReferenceException

>Failed to fetch timeouts from the timeout storage
System.NullReferenceException: Object reference not set to an instance of an object.
  at NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver.Poll(Object obj) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Timeout\Hosting\Windows\TimeoutPersisterReceiver.cs:line 88
  at System.Threading.Tasks.Task.Execute()

It seems that version 6.2.3 part of Particular/NServiceBus#2885 that introduced `IPersistTimeoutsV2` caused this NRE behavior and that the backwards compatibility on the `IPersistTimeouts` interface is not working.

Reason for it not working is that the implementations inherit both `IPersistTimeouts` and `IPersistTimeoutsV2`. If a separate V2 implementation was added there would not be a runtime dependency on `IPersistTimeoutsV2`.

## Comparing to NServiceBus.RavenDB

Looking at package NServiceBus.RavenDB version 3.0.4 that introducted  `IPersistTimeoutsV2` and that is targeting atleast NServiceBus 5.2.8

## Howto reproduce it

- Copy/clone http://docs.particular.net/samples/hosting/nservicebus-host/
- Add latest version of `NServiceBus.NHibernate` package
- Configure it to use NServiceBus.NHibernate
- Run it and see that it works as expected
- Downgrade `NServiceBus` to 5.2.7
- Run it again and soon you see a NRE

Notice that NHibernate is not initialized at all.

All the latest versions of other official transports target at least NServiceBus v5.2.8 which makes NServiceBus to be automatically updated if they add these (latest) transport packages to their project via the nuget management UI and this behavior cannot occur.

However this exception can still occur with other transports too if updating to a specific older version:

* NServiceBus.RavenDB v2.1.2 & NServiceBus v5.2.7
* NServiceBus.Azure v6.1.5 & NServiceBus v5.2.7

## References

- https://github.com/Particular/NServiceBus/issues/2885
- https://github.com/Particular/NServiceBus.NHibernate/releases/tag/6.2.3
- https://github.com/Particular/NServiceBus.RavenDB/releases/tag/3.0.4
- https://www.nuget.org/packages/NServiceBus.NHibernate/6.2.3
- https://www.nuget.org/packages/NServiceBus.RavenDB/3.0.4

**Comment by ramonsmits** [comment]
The cause is that the implementation is not backwards compatible as it has a runtime dependency on the V2 interface which is not available in pre NServiceBus v5.2.8

**Comment by ramonsmits** [comment]
All the latest versions of other official transports target at least NServiceBus v5.2.8 which makes NServiceBus to be automatically updated if they add these (latest) transport packages to their project via the nuget management UI and this behavior cannot occur.

However this exception can still occur with other transports too if updating to a specific older version:

* NServiceBus.RavenDB v2.1.2 & NServiceBus v5.2.7
* NServiceBus.Azure v6.1.5 & NServiceBus v5.2.7
