### ISSUE TITLE
Installers blow up when used with Ninject

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.NHibernate#187]
Version: Latest beta 6

### To repro

Use the `samples\nhibernate\custom-mappings\NHibernate_7` sample, install ninject, configure it to just ninject, start.

### Exception

```
Ninject.ActivationException was unhandled
  HResult=-2146233088
  Message=Error activating IntPtr
No matching bindings are available, and the type is not self-bindable.
Activation path:
  3) Injection of dependency IntPtr into parameter method of constructor of type Func{string, Task}
  2) Injection of dependency Func{string, Task} into parameter execute of constructor of type Installer+SchemaUpdater
  1) Request for Installer+SchemaUpdater

Suggestions:
  1) Ensure that you have defined a binding for IntPtr.
  2) If the binding was defined in a module, ensure that the module has been loaded into the kernel.
  3) Ensure you have not accidentally created more than one kernel.
  4) If you are using constructor arguments, ensure that the parameter name matches the constructors parameter name.
  5) If you are using automatic module loading, ensure the search path and filters are correct.

  Source=Ninject
  StackTrace:
       at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
       at Ninject.KernelBase.Resolve(IRequest request)
       at Ninject.Planning.Targets.Target`1.GetValue(Type service, IContext parent)
       at Ninject.Planning.Targets.Target`1.ResolveWithin(IContext parent)
       at Ninject.Activation.Providers.StandardProvider.GetValue(IContext context, ITarget target)
       at Ninject.Activation.Providers.StandardProvider.<>c__DisplayClass5.<Create>b__2(ITarget target)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
       at Ninject.Activation.Context.ResolveInternal(Object scope)
       at Ninject.Activation.Context.Resolve()
       at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
       at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
       at Ninject.KernelBase.Resolve(IRequest request)
       at Ninject.Planning.Targets.Target`1.GetValue(Type service, IContext parent)
       at Ninject.Planning.Targets.Target`1.ResolveWithin(IContext parent)
       at Ninject.Activation.Providers.StandardProvider.GetValue(IContext context, ITarget target)
       at Ninject.Activation.Providers.StandardProvider.<>c__DisplayClass5.<Create>b__2(ITarget target)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
       at Ninject.Activation.Context.ResolveInternal(Object scope)
       at Ninject.Activation.Context.Resolve()
       at Ninject.KernelBase.<>c__DisplayClass13.<Resolve>b__d(IBinding binding)
       at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
       at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
       at NServiceBus.Deduplication.NHibernate.Installer.Installer..ctor(IBuilder builder) in C:\BuildAgent\work\5135de308b2f3016\src\NServiceBus.NHibernate\Deduplication\Installer\Installer.cs:line 15
       at DynamicInjectorc882e4f4fdfa42dfab8af95361ecdb67(Object[] )
       at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
       at Ninject.Activation.Context.ResolveInternal(Object scope)
       at Ninject.Activation.Context.Resolve()
       at Ninject.KernelBase.<>c__DisplayClass13.<Resolve>b__d(IBinding binding)
       at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
       at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
       at NServiceBus.StartableEndpoint.<RunInstallers>d__5.MoveNext() in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 93
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 43
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NServiceBus.Endpoint.<Start>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Endpoint.cs:line 28
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Program.<AsyncMain>d__1.MoveNext() in C:\dev\docs.particular.net\samples\nhibernate\custom-mappings\NHibernate_7\Sample.XmlMapping\Program.cs:line 39
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Program.Main() in C:\dev\docs.particular.net\samples\nhibernate\custom-mappings\NHibernate_7\Sample.XmlMapping\Program.cs:line 14
  InnerException: 

```

**Comment by andreasohlund** [comment]
I wonder if this is an NInject issue, I was able to repro it with this code:

```
namespace NServiceBus.Ninject.Tests
{
    using System;
    using global::Ninject;
    using NServiceBus.ObjectBuilder;
    using NServiceBus.ObjectBuilder.Ninject;
    using NUnit.Framework;

    public class InjectingFuncs
    {
        [Test]
        public void ShouldWork()
        {
            var kernel = new StandardKernel();
            var builder = new NinjectObjectBuilder(kernel);

          
            builder.Configure(typeof(ClassThatDependsIBuilder), DependencyLifecycle.InstancePerCall);
            builder.Configure(() => new ClassWithFuncDep(()=> ""), DependencyLifecycle.SingleInstance);

            builder.Build(typeof(ClassThatDependsIBuilder));
        }

        class ClassThatDependsIBuilder
        {
            public ClassThatDependsIBuilder(IBuilder builder)
            {
                builder.Build<ClassWithFuncDep>();
            }
        }
        public class ClassWithFuncDep
        {
            public ClassWithFuncDep(Func<string> someFunc)
            {
            }
        }
    }
}
```

**Comment by andreasohlund** [comment]
@Particular/container-maintainers ideas?

**Comment by WilliamBZA** [comment]
Will dig into it tomorrow, but perhaps it has a similar fix to [this](https://github.com/Particular/NServiceBus.CastleWindsor/issues/8) issue?

**Comment by andreasohlund** [comment]
Yea, I'd say stop using funcs in NH is the safest move

**Comment by andreasohlund** [comment]
We can just pass a `bool noOp` to the installer

**Comment by andreasohlund** [comment]
Turns out a boolean flag blows up as well. This looks like a ninject bug, debugging this with @danielmarbach , repro here:

https://github.com/Particular/NServiceBus.Ninject/tree/ninject-bug

**Comment by danielmarbach** [comment]
@andreasohlund your approach works. I just verified it again by extending the tests see https://github.com/Particular/NServiceBus.Ninject/commit/5100d560cd44e05453a3cc3643448150ca539292

![image](https://cloud.githubusercontent.com/assets/174258/15389039/2daf94ec-1db5-11e6-9c74-ab00dff53eb7.png)

**Comment by andreasohlund** [comment]
Found a workaround, we'll use the settings dictionary instead. Will create  a PR, stay tuned

**Comment by WilliamBZA** [comment]
Perhaps this is a silly question, but is it not worth just doing the change from `Func<>` instead of all the workarounds?

Specifically for the CastleWindsor issue, the change would take 5 minutes (excluding releasing + smoketesting). It wasn't done because that was before the maintainer budgets were introduced.

Is it not a similar case here? Are we not spending more time finding workarounds than a proper fix would take?

**Comment by danielmarbach** [comment]
@williambza The proper fix would be to fix the installers which is a larger
issue.

**Comment by andreasohlund** [comment]
My fix won't need func ctors
